### ISSUE TITLE
Квадратное уравнение

### ISSUE THREAD

**Issue by ankutalev** [hardworkar/aemorozov_19214#1]
1) А модуль-то Вам зачем?  - 0 == 0, так-то
2) Дискриминант торчит наружу, он должен быть вложенной функцией в функции решения квадратного уравнения
3) Аналогично про x1 x2
4)| True = Рад, что Вы это запомнили, однако для такой цели нужно использовать| otherwise
5) Портянку из гвардов га граничные условия лучше переписать на паттерн матчинг

**Comment by brocbyte** [comment]
Поправил, вроде
Посмотрите, пожалуйста

**Comment by ankutalev** [comment]
Отрицательный дискриминант потерялся

**Comment by brocbyte** [comment]
Поправил, снова вроде
Посмотрите снова, пожалуйста

**Comment by ankutalev** [comment]
Принято
